### ISSUE TITLE
In regards to the question: Will the media queries trigger the clinthintpixel.gif request before the first inline image is requested?

### ISSUE THREAD

**Issue by bjankord** [knightdr/clienthintpixel#1]
I don't believe this is possible. As both the request for the media queries which trigger the clinthintpixel.gif and the ones for the inline images will be in the same initial page request. 

I will try and explain in simple terms that I understand.

A device requests a website. The server sends over data to the device for the requested site. While there are multiple requests, and a request for CSS would, I believe happen before inline images, they are all part of the "initial" request. 

So even though we could set a cookie or pass url parameters on an image, we cannot use data from the cookies or the url parameters on the image to alter other parts of the initial request. We can only use that data on subsequent page views.

For something like this to work, we would need to be able to split up of initial request. The first part for collecting that data and sending it back to the server before the rest of our initial request is sent.

If there is some way to do this, I'd be glad to hear it. I've heard talk of possibly being able to do this with node.js but I'm not familiar with it to know if this is true.

**Comment by knightdr** [comment]
@bjankord 

This makes perfect sense. I guess I was hoping that if the clienthintpixel.gif was requested first then subsequent requests for images could get routed by the server based on that initial request for clienthintpixel.gif. My knowledge in this area is very limited so wishing, hoping and reaching out to others was where my mind went first.

**Comment by bjankord** [comment]
I would recommend checking out the Filament Groups experiment with responsive images from a few years ago. https://github.com/filamentgroup/Responsive-Images It may be of interest if you are wanting to explore this technique some more. 

Its always good to hear others ideas. Responsive images is a good problem that could use discussion like this. Cheers!
